development:
  host: localhost
  adapter: postgresql
  database: bailbetterlandingpage_development

staging:
  adapter: postgresql
  database: bailbetterlandingpage_staging

production:
  adapter: postgresql
  database: bailbetterlandingpage_production

test:
  host: localhost
  adapter: postgresql
  database: bailbetterlandingpage_test